# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    tags:
      - "v*.*.*"
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: ⚙️ Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter

      - name: 💻 Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.4"
          channel: "stable"

      - name: 📝 Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: 📦 Pub get
        run: flutter pub get

      - name: 🔍 Analyze project source
        run: dart analyze

      - name: 🔨 (Release) Setup Java
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: 🔨 (Release) Build apk
        if: startsWith(github.ref, 'refs/tags/v')
        run: flutter build apk

      - name: 🚀 (Release) Release to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/app/outputs/apk/release/app-release.apk
          body: ${{ github.event.head_commit.message }}
